# Generated by Django 2.2.24 on 2021-10-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alarme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_humain', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='autorisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('categorie', models.CharField(max_length=20)),
                ('numtel', models.IntegerField()),
                ('status_lampe', models.BooleanField()),
                ('status_alarme', models.BooleanField()),
                ('psswd', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='View_lp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_int', models.IntegerField(null=True)),
                ('id_lampe', models.CharField(max_length=30)),
                ('status', models.BooleanField()),
                ('date_alum', models.CharField(max_length=30)),
                ('date_ext', models.CharField(max_length=30)),
                ('nom_humain', models.CharField(max_length=20)),
                ('consomation', models.FloatField(null=True)),
                ('consomation_f', models.FloatField(null=True)),
            ],
        ),
    ]
