# Generated by Django 2.2.24 on 2021-10-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view_lp',
            name='id_int',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
