# Generated by Django 2.2.24 on 2021-10-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_auto_20211013_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view_lp',
            name='id_int',
            field=models.IntegerField(null=True),
        ),
    ]
