# Generated by Django 2.2.24 on 2021-10-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_auto_20211013_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='autorisations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('categorie', models.CharField(max_length=20)),
                ('numtel', models.IntegerField()),
                ('status_lampe', models.BooleanField()),
                ('status_alarme', models.BooleanField()),
                ('psswd', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
