# Generated by Django 2.2.24 on 2021-10-13 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0004_autorisations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='autorisations',
        ),
    ]
