# Generated by Django 2.2.24 on 2021-10-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0005_delete_autorisations'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarme',
            name='consomation',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='alarme',
            name='consomation_f',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='alarme',
            name='date_alum',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='alarme',
            name='date_ext',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='alarme',
            name='id_int',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alarme',
            name='id_lampe',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='alarme',
            name='nom_humain',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
